version: "3.8"

services:
  mysql-container:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: BitBasket_ProductsDb
    ports:
      - "3307:3306"
    volumes:
      - ./Docker/mysql_init:/docker-entrypoint-initdb.d
    networks:
      - ecommerce-network
    hostname: mysql-container
  
  product-microservice:
    image: damonsahil26/ecommerce-product-microservice:latest
    environment:
      MYSQL_PASSWORD: admin
      MYSQL_HOST: mysql-container
    ports: 
      - 8080:8080
    networks:
      - ecommerce-network

  postgres-container:
    image: postgres:16.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: BitBucket.Users
    ports:
      - 5432:5432
    volumes:
      - ./Docker/postgres_init:/docker-entrypoint-initdb.d
    networks:
      - ecommerce-network
   
  user-microservice:
    image: damonsahil26/ecommerce-user-microservice
    environment:
      POSTGRE_HOST: postgres-container
      POSTGRE_PASSWORD: admin
    ports: 
      - 9090:9090
    networks:
      - ecommerce-network    
   
networks:
 ecommerce-network:
  driver: bridge